# Generated by Django 6.0.5 on 2026-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='company/')),
                ('short_description', models.TextField(help_text='Текст для карточки')),
                ('content', models.TextField(help_text='Полный текст статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья компании',
                'verbose_name_plural': 'Статьи компании',
            },
        ),
    ]
