# Generated by Django 6.0.5 on 2026-06-07 16:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Полный текст статьи'),
        ),
    ]
