# Generated by Django 6.0.5 on 2026-06-11 10:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Резюме на позицию')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Город проживания')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('desired_salary', models.CharField(blank=True, max_length=100, verbose_name='Желаемая заработная плата')),
                ('employment_type', models.CharField(blank=True, choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('remote', 'Удалённая работа'), ('internship', 'Стажировка')], max_length=20, verbose_name='Тип занятости')),
                ('ready_to_relocate', models.BooleanField(default=False, verbose_name='Готов к переезду')),
                ('goal', models.TextField(blank=True, verbose_name='Цель')),
                ('company1', models.CharField(blank=True, max_length=255, verbose_name='Компания 1')),
                ('position1', models.CharField(blank=True, max_length=255, verbose_name='Должность 1')),
                ('work_from1', models.DateField(blank=True, null=True, verbose_name='Период работы с 1')),
                ('work_to1', models.DateField(blank=True, null=True, verbose_name='Период работы по 1')),
                ('functions1', models.TextField(blank=True, verbose_name='Выполняемые функции 1')),
                ('company2', models.CharField(blank=True, max_length=255, verbose_name='Компания 2')),
                ('position2', models.CharField(blank=True, max_length=255, verbose_name='Должность 2')),
                ('work_from2', models.DateField(blank=True, null=True, verbose_name='Период работы с 2')),
                ('work_to2', models.DateField(blank=True, null=True, verbose_name='Период работы по 2')),
                ('functions2', models.TextField(blank=True, verbose_name='Выполняемые функции 2')),
                ('company3', models.CharField(blank=True, max_length=255, verbose_name='Компания 3')),
                ('position3', models.CharField(blank=True, max_length=255, verbose_name='Должность 3')),
                ('work_from3', models.DateField(blank=True, null=True, verbose_name='Период работы с 3')),
                ('work_to3', models.DateField(blank=True, null=True, verbose_name='Период работы по 3')),
                ('functions3', models.TextField(blank=True, verbose_name='Выполняемые функции 3')),
                ('education', models.CharField(blank=True, choices=[('secondary', 'Среднее'), ('college', 'Среднее специальное'), ('bachelor', 'Бакалавр'), ('specialist', 'Специалист'), ('master', 'Магистр'), ('phd', 'Кандидат наук')], max_length=20, verbose_name='Образование')),
                ('languages', models.TextField(blank=True, verbose_name='Знание языков')),
                ('extra_info', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('personal_qualities', models.TextField(blank=True, verbose_name='Личные качества')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Требования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
