# Generated by Django 6.0.5 on 2026-06-24 11:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_kz',
            field=models.TextField(blank=True, verbose_name='Описание (KZ)'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Полный текст (EN)'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='content_kz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Полный текст (KZ)'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='short_description_kz',
            field=models.TextField(blank=True, verbose_name='Краткое описание (KZ)'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (KZ)'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='cover',
            field=models.ImageField(upload_to='albums/covers/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(),
        ),
    ]
