# Generated by Django 6.0.5 on 2026-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
