# Generated by Django 6.0.5 on 2026-06-09 15:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=django_ckeditor_5.fields.CKEditor5Field(default='default text', help_text='Показания к применению'),
            preserve_default=False,
        ),
    ]
