# Generated by Django 6.0.5 on 2026-06-24 11:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Показания (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_kz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Показания (KZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_kz',
            field=models.TextField(blank=True, verbose_name='Краткое описание (KZ)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (KZ)'),
        ),
    ]
